### ISSUE TITLE
Troubleshooting non-matches ?

### ISSUE THREAD

**Issue by udf2457** [bramus/router#26]
Hi,

I'm really struggling to get bramus/router to work on my setup (NGINX + PHP7), I have no problems at all with aura/router, but nothing I do seems to get bramus to match ! The only reason I'm being forced to use bramus is because of your support for "before" which aura doesn't.

What is the recommended methodology to troubleshoot the route matching process ?  The bramus docs seem to make no mention of this, they simply assume everything "just works".

Thanks !

**Comment by sant0ro** [comment]
Hello, just see the Documentation. `bramus/router` uses REGEX paths for matching. You also can customize it. The Router works like a Path Finder algorithm, you can customize it with the Requested Method, and Deep Rules (like as sub-nodes and sub-levels of main-tree).

See the examples. Also you can check what is going on, with creating the 404 Router, and "echoing" the output of the Router.

As i saw `aura/router` is a lot more complex and with a lot more codes, that in my opinion are useless. `bramus/router` does a quite job with less complex algorithms. I rate this router as an Linear Complexion Algorithm "O(N)". Since the finder need one one deep iteration to see all possible  paths. You can also customize our create a more advanced elevated-router by using `bramus/router` as an extended base. It's the same as what i do. I use `bramus/router` to implemente a IDA* Path Finding for URIS with less complex, for my CMS.

Good luck!

**Comment by udf2457** [comment]
Hi sant0ro, thanks for the super quick reply.   Sounds like maybe "creating the 404 router" is the missing piece of the puzzle for me, at the moment I'm getting 404s in a very simple configuration with paths that work perfectly in Aura and not at all in bramus.

**Comment by udf2457** [comment]
@sant0ro P.S. The main benefit of Aura is it is fully PSR compliant. ;-)

**Comment by bramus** [comment]
Hi @udf2457,

As @sant0ro mentioned route matching is done via static route patterns, or via regexes. [This is mentioned in the documentation](https://github.com/bramus/router#route-patterns). You can test your regexes using tools such as https://regex101.com/

Creating a 404 catcher [is also mentioned in the documentation](https://github.com/bramus/router#custom-404). You can always `var_dump()` your Bramus/Router instance in the callable to see which routes have been mounted.

The source of [the included demo](https://github.com/bramus/router/blob/master/demo/index.php) should also be of help.

Closing this issue for now, as it's not an actual issue with the router code, but with the implementation. Do feel free to keep on commenting on this issue in order to get more help.

Regards,
Bramus.

**Comment by udf2457** [comment]
Hi @bramus, thanks for that. The bramus docs do indeed "mention" creating a 404 catcher, but doesn't actually provide much of a concrete example .... I'm guessing the answer is var_dump($router), but maybe instead of the docs saying "//do someting useful" you could actually give an example ?

**Comment by sant0ro** [comment]
@udf2457 as i see the documentation of bramus is really bigger than from aura. 

`$router->set404(function() {
 var_dump($router);
});`

You also can pass parameters in the function, since is an anonymous functions, depending the deepness of the path, and how you are using/invoking the router, you can use different variables depending of how you want to do something.

Recommending you to debug your PHP application through IDE's like PHPStorm, or simply, able entirely PHP Log, in error_reporting(E_ALL + E_INFO);

You can also se Apache log, to see what is happening with your application.

**Comment by udf2457** [comment]
`$router->set404(function() { var_dump($router); });`

just prints "NULL"

I have simplified your demo code

```
<?php
// Require composer autoloader
require 'vendor/autoload.php';

// Create a Router
$router = new \Bramus\Router\Router();

// Custom 404 Handler
$router->set404(function() {
        header('HTTP/1.1 404 Not Found');
         var_dump($router);
        echo '404, route not found!';
});

// Static route: / (homepage)
$router->get('demo/test2.php/', function() {
        echo '<h1>bramus/router</h1><p>Try these routes:<p><ul><li>/hello/<em>name</em></li><li>/blog</li><li>/blog/<em>year</em></li><li>/blog/<em>year</em>/<em>month</em></li><li>/blog/<em>year</em>/<em>month</em>/<em>day</em></li></ul>';
});

// Dynamic route: /hello/name
$router->get('/hello/(\w+)', function($name) {
        echo 'Hello ' . htmlentities($name);
});

// Thunderbirds are go!
$router->run();
```

No matter what options I try for the "// Static route: / (homepage)" section I always get 404, even if I use the same path parameter that works fine with Aura

**Comment by sant0ro** [comment]
Just 
<pre>
// Custom 404 Handler
$router->set404(function() use ($router) {
        header('HTTP/1.1 404 Not Found');
         var_dump($router);
        echo '404, route not found!';
});
</pre>

**Comment by udf2457** [comment]
Old dog new tricks... I was barely aware of that use of use() !
