### ISSUE TITLE
Return route result

### ISSUE THREAD

**Issue by softius** [bramus/router#3]
When executing the route function in `Router::run` method, it would be really helpful if the result of route function was available outside of run method. For instance, I was expecting to be able to 

```
$response = $router->run();
```

This will allow me to implement a default view behaviour for controllers. Here is an example

```
$router->get('/hello/(w+)', function($name) {
  return 'Hi '. $name;
});
```

Or even to return a result array

```
$router->get('/api/users', function() { 
   return $users->findAll();
});
```

**Comment by tleb** [comment]
In my process of customizing this class, I wanted to extend the `run()` method. What I wanted to do is act if no route where executed. This could be done by simply having `run()` which returns true if a route was executed, and false otherwise.

I post this here because it is linked to the return value of `Router::run`, even though it is not the same request.

Also, could a parameter `$execute_404` be added to `Router::run` (set to true by default, and must be a boolean).

**Comment by bramus** [comment]
@tleb: To achieve this you can define a wildcard route as the very last in your which acts as a _catchall_, as `bramus/router` only executes the first route matched :-)

**Comment by RinkAttendant6** [comment]
Instances of the [interoperable ("standardized") `\Psr\Http\Message\ResponseInterface`](http://www.php-fig.org/psr/psr-7/) are immutable value objects. Using one with this package is impossible because manipulating the response object would create a new instance. This new instance cannot be used beyond the scope of the callback function if it can't be returned.

Please consider at least making it an option to capture the response(s).

**Comment by sant0ro** [comment]
@RinkAttendant6 in fact your statement can be true, but in this context is wrong.
Responses aren't immutable value objects. Of course aren't!.
The pattern of a response, of course is the same, modeled by a protocol. In this case you issued the HTTP Message Interface, that in my opinion is relative.

The job of the Routeris exactly how @bramus said. Routing. Nothing more. I see a lot of Routing libraries for PHP on GitHub, but they are big, or heavy made, or loss the meaning of what a Router is.

The suggestion of this issue, is a specific use case, convenient for someone.
A Router can't return a Response. A Router can have a Callback. 

Purpose of the latest accepted Pull Request, that expands the ways of invoking a callback.

You can as yourself create a Response class. And handle the Response at your own way. Responses are really different, and changes easily depending the context.

As example we can have jSON responses, HTML responses, HTTP code responses, RAW, Images, Blobs, and so much more. Forcing to the end-user to use a specific Response Handler only will difficult the engine, and the "business rule".

Good point, but you missed in some aspects.

Waiting @bramus opinion.
