### ISSUE TITLE
Get ID from watch.php?id=123abc

### ISSUE THREAD

**Issue by ArdiArtani** [bramus/router#50]
Hello,

How can I do something like this?
`http://mydomain.com/watch.php?id=123abc` I want to get the $id.

I tried the code below but it didn't work
```
$router->get('/watch.php?id=(\w+)', function($id) {
    echo $id;
});
```
I want to use this route method as an alternative.

**Comment by sant0ro** [comment]
But it's exactly like that. Literally. Or just 

<pre>
```php
$router->get('/watch.php?id={id}', function($id) {
    echo $id;
});
```

**Comment by sant0ro** [comment]
Remember, that a router need have a path likeable syntax. Doesn't make sense you use a route and say that the route needs to be `watch.php`, why just not `watch/{id}` eg.: `watch/1`

**Comment by ArdiArtani** [comment]
@sant0ro I already am using `watch/{id} and v/{id}` but before I started using the bramus router I had users who shared their videos using the `watch.php?id={id}`. That's why I want to use the `watch.php?id={id}` option too. Btw the code above is not working.

**Comment by bramus** [comment]
I’d recommend to redirect all `watch.php?id={id}` routes to `/watch/{id}` (which is handled by your router if I understand correctly)
 
You can do this by either:
- leaving a watch.php file in place and use a PHP redirect
- using a webserver rewrite (e.g. `.htaccess` on Apache)

**Comment by ArdiArtani** [comment]
@bramus Thanks but I managed to do something else instead using the code below

```
$router->get('/watch.php', function () {
	$id = htmlentities($_GET['id']);
	if($id){
		redirect_to(SITEURL."v/".$id);
	}
});
```

**Comment by sant0ro** [comment]
@bramus did you agree that would be amazing a method to get php input variables as a Collection? Like Laravel does?

It's basically a 
```php
$collection = file_get_contents("php://input");
```

with some data filtering. It retrvies the request body (PUT, POST, etc)

And something for Query String if exists.

Idk, because laravel has a method like `request()->all()` that retrieves either jSON body (in POST, PUT) or Query String in GET. (it combines both if both jSON body and Query String exists.).
