### ISSUE TITLE
Cyrillics issue

### ISSUE THREAD

**Issue by notom** [bramus/router#80]
Hi guys,

I have a website with Cyrillic text slugs. For example: domain.com/bg/това-е-слъг
Currently the router does not work on Cyrillic text. So I had to change your code in Route.php, 341row:

`$route['pattern'] = preg_replace('/{([A-Za-z]*?)}/', '(\w+)', $route['pattern']);`

to

`$route['pattern'] = preg_replace('/{([A-Za-zа-яА-Я]*?)}/', '(\w+)', $route['pattern']);`

I hate changing original code and it's not the best solution, so maybe you can do something about the cyrillics in the next push.

Thank you!

**Comment by necmettin** [comment]
It should be more than that IMHO. Anything that is not a control character should be usable maybe?

**Comment by bramus** [comment]
I see that Laravel [uses](https://github.com/illuminate/routing/blob/master/Route.php#L456) `'/\{(.*?)\}/'` as the pattern to extract parameters.

I'll gladly accept a PR containing the change (+ accompanying tests) :-)

**Comment by fscchan** [comment]
I propose to change the line 344

```if (preg_match_all('#^'.$route['pattern'].'$#', $uri, $matches, PREG_OFFSET_CAPTURE)) {```

to 

```if (preg_match_all('#^'.$route['pattern'].'$#u', $uri, $matches, PREG_OFFSET_CAPTURE)) {```

So that the router allow unicode character according to https://stackoverflow.com/a/38938931

**Comment by fscchan** [comment]
Apparently $_SERVER["REQUEST_URI"] encodes non-latin and symbols to RFC-3986 and needs to be [decoded(http://php.net/manual/en/function.rawurldecode.php) before the route matching.

**Comment by bramus** [comment]
I've just pushed some things to `master`. Looking forward to your feedback.

The problem here was twofold:

1. Support for Cyrillic/astral/etc. Symbols in route pattern values (e.g. make it so that `/hello/💩` matches the route pattern `/hello/{name}`)
2. Support for Cyrillic/astral/etc. Symbols in route placeholder names (e.g. make it so that `/hello/bramus` matches the route pattern `/hello/{име}`)

I've done two separate commits to tackle this:

1. Support for Cyrillic/astral/etc. Symbols in route pattern values: 0f4733d9fe30cd502f1f26ebb2c9d4d36dbd4775
2. Support for Cyrillic/astral/etc. Symbols in route placeholder names: ae0db20708e17708c8135251b8fa34bf2a6c5f96

Feel free to test this from `dev-master` _(Circle CI says [all is fine](https://travis-ci.org/bramus/router/builds/493309154))_. If well received I'll tag it as a new release.

**Comment by fscchan** [comment]
I might have misunderstood this issue. I thought it was about supporting unicode characters on the route itself.

My bad.

**Comment by bramus** [comment]
@fscchan Yeah, that was my first impression too. Took me a while to notice that the original poster was adjusting the regex part for the placeholders _(e.g. `{var}` in a route pattern)_.

While I was at it, I thought I'd just fix both cases ;)

**Comment by bramus** [comment]
FYI: Version 1.4 got tagged and released.

**Comment by notom** [comment]
Yes! That worked. 
Just one more thing: somewhere in getCurrentUri  function the text should be urldecode-ed

**Comment by bramus** [comment]
Will take a look into it.

**Comment by fscchan** [comment]
>somewhere in getCurrentUri function the text should be urldecode
I referenced that on [this comment](https://github.com/bramus/router/issues/80#issuecomment-463041893)
